version: '2'
services:
    web:
        build: ./web
        command: npm start
        environment:
            PORT: 3000
            API_HOST: 'myapi'
            API_PORT: 4000
        ports:
            - 3000:3000
        depends_on:
            - myapi
    myapi:
        build: ./api
        command: node_modules/.bin/nodemon --exec npm start
        environment:
            PORT: 4000
        ports:
            - "4000:4000"
        #volumes:
            #- ./api:/home/api
